### ISSUE TITLE
Problem with the make command

### ISSUE THREAD

**Issue by arnabp893** [aida-alvera/DINEOF#14]
I am tryin to work with my gappy data. 
I am having trouble while using the command make.

arnab@Arnab ~/DINEOF
$ cp config.mk.template config.mk

arnab@Arnab ~/DINEOF
$ make
Makefile:30: Compilers/Windows_NT-gfortran.mk: No such file or directory
make: *** No rule to make target 'Compilers/Windows_NT-gfortran.mk'.  Stop.

ANy help will be appreciated. 
thank you

**Comment by ctroupin** [comment]
I guess you are working with a machine running under Windows.
Have you already installed a compiler? 

Usually for Windows we work with `cygwin` or `mingw`.

**Comment by arnabp893** [comment]
Yes I am using cygwin. I have not installed any compiler. Is there any specific compiler I have to download before downloading DINEOF?

**Comment by ctroupin** [comment]
yes, you need a Fortran compiler.
I think it's explained here: https://github.com/aida-alvera/DINEOF?tab=readme-ov-file#installation-from-source

**Comment by arnabp893** [comment]
Yes I have gcc fortran compiler added to the cygwin as a dependency
Is there something I am missing?
I followed all the instructions in the GitHub page

**Comment by ctroupin** [comment]
you also need the netCDF library and the Arpack library.

**Comment by arnabp893** [comment]
So far the installed libraries are gcc-fortran, make, libarpack-devel, liblapack-devel, libnetcdf-fortran-devel, git for the cygwin and I also have to download Arpack and netcdf?
I thought the arpack and fortran libs are for linux users.

**Comment by ctroupin** [comment]
OK, maybe you can try again the compilation now, and copy here the error message (if it fails).

All the libraries are needed, whatever the operating system.

**Comment by arnabp893** [comment]
arnab@Arnab ~
$ git clone https://github.com/Aida-ALvera/DINEOF
Cloning into 'DINEOF'...
remote: Enumerating objects: 434, done.
remote: Counting objects: 100% (110/110), done.
remote: Compressing objects: 100% (66/66), done.
remote: Total 434 (delta 45), reused 98 (delta 37), pack-reused 324
Receiving objects: 100% (434/434), 14.70 MiB | 9.33 MiB/s, done.
Resolving deltas: 100% (192/192), done.

arnab@Arnab ~
$ cd DINEOF/

arnab@Arnab ~/DINEOF
$ cp config.mk.template config.mk

arnab@Arnab ~/DINEOF
$ make
Makefile:30: Compilers/Windows_NT-gfortran.mk: No such file or directory
make: *** No rule to make target 'Compilers/Windows_NT-gfortran.mk'.  Stop.

I have attached the whole compilation

**Comment by ctroupin** [comment]
OK, it says that the file `Windows_NT-gfortran.mk`doesn't exist, in fact in the repository `Compilers`, you will find those:
```bash
IRIX-f90.mk
libs.mk
Linux-g95.mk
Linux-gfortran.mk
Linux-ifort.mk
Linux-pgi.mk
mingw-gfortran.mk
```

**Comment by arnabp893** [comment]
Yes, I checked my compilers  drive and there is no .mk file named Windows_NT-gfortran.mk. 
so how do we get Windows_NT-gfortran.mk?

**Comment by ctroupin** [comment]
For Windows you can install the compilers, libraries etc with [`cygwin`](https://www.cygwin.com/), then following the README:

> For Cygwin, OS in config.mk should be Linux (default).

**Comment by arnabp893** [comment]
I opened config.mk
and I found this,
`
#-------------------------------#
#  Platform specific variables  #
#-------------------------------#

OS ?= Linux

# Compiler (gfortran (default), ifort, pgi, g95)

FORT ?= gfortran

`
the os is Linux by default.

**Comment by ctroupin** [comment]
yes, and if you work with Windows + Cygwin, the doc says to put `Linux` as the OS in `config.mk`

**Comment by arnabp893** [comment]
I'm following all the instructions in the readme file but it looks like the OS is automatically coming up as Linux

**Comment by arnabp893** [comment]
still getting the same error message

**Comment by arnabp893** [comment]
Alright I used windows subsystem method and I assume it worked cause it did not give me any error. May be it was a cygwin issue.
Thanks for your help.
