### ISSUE TITLE
Can you please provide the update link of dineof.exe?

### ISSUE THREAD

**Issue by Mr-Nobody-dey** [aida-alvera/DINEOF#15]
**"http://modb.oce.ulg.ac.be/mediawiki/index.php/DINEOF" -> link is broken.**

**Comment by ctroupin** [comment]
Hello, 
sorry I don't remember what was there at that link, is it the Windows executable that you need?

**Comment by Mr-Nobody-dey** [comment]
yes.

**Comment by ctroupin** [comment]
Personally I don't have the `.exe`, I'm wondering if we can add a GitHub action that automatically compile the code and then provide the result as an artifact.  

Did you try to compile the code yourself? We can help if needed.

**Comment by Mr-Nobody-dey** [comment]
Ok. I will try to compile the code. And if need help I will ask here. Thanks again.
