### ISSUE TITLE
Issue with running DINEOF.

### ISSUE THREAD

**Issue by Mr-Nobody-dey** [aida-alvera/DINEOF#16]
I am using "Ubuntu 16.04.7 LTS"., I am following the procedures of compiling as mentioned in the github repositiory,
(Although I am not sure if it is the right way to run the code.) 
->
"git clone https://github.com/Aida-Alvera/DINEOF
cd DINEOF/
cp config.mk.template config.mk
make"

Outputs of compilation: After running make
"
gfortran -fimplicit-none -O3 -ffast-math -fdefault-real-8 -fconvert=big-endian -frecord-marker=4 -DDOUBLE_PRECISION -I/usr/include   -c ufileformat.F90
gfortran -fimplicit-none -O3 -ffast-math -fdefault-real-8 -fconvert=big-endian -frecord-marker=4 -DDOUBLE_PRECISION -I/usr/include   -c initfile.F90
gfortran -fimplicit-none -O3 -ffast-math -fdefault-real-8 -fconvert=big-endian -frecord-marker=4 -DDOUBLE_PRECISION -I/usr/include   -c ReadMatrix.F90
gfortran -fimplicit-none -O3 -ffast-math -fdefault-real-8 -fconvert=big-endian -frecord-marker=4 -DDOUBLE_PRECISION -I/usr/include   -c stat.F90
gfortran -fimplicit-none -O3 -ffast-math -fdefault-real-8 -fconvert=big-endian -frecord-marker=4 -DDOUBLE_PRECISION -I/usr/include   -c norm.F90
gfortran -fimplicit-none -O3 -ffast-math -fdefault-real-8 -fconvert=big-endian -frecord-marker=4 -DDOUBLE_PRECISION -I/usr/include   -c dineof_utils.F90
gfortran -fimplicit-none -O3 -ffast-math -fdefault-real-8 -fconvert=big-endian -frecord-marker=4 -DDOUBLE_PRECISION -I/usr/include   -c smeanToZero.F
gfortran -fimplicit-none -O3 -ffast-math -fdefault-real-8 -fconvert=big-endian -frecord-marker=4 -DDOUBLE_PRECISION -I/usr/include   -c smeanByRow.F
gfortran -fimplicit-none -O3 -ffast-math -fdefault-real-8 -fconvert=big-endian -frecord-marker=4 -DDOUBLE_PRECISION -I/usr/include   -c svariExp.F
gfortran -fimplicit-none -O3 -ffast-math -fdefault-real-8 -fconvert=big-endian -frecord-marker=4 -DDOUBLE_PRECISION -I/usr/include   -c ssvd_lancz.F
gfortran -fimplicit-none -O3 -ffast-math -fdefault-real-8 -fconvert=big-endian -frecord-marker=4 -DDOUBLE_PRECISION -I/usr/include   -c dineof.F90
gfortran   -o dineof ReadMatrix.o ufileformat.o initfile.o stat.o norm.o dineof_utils.o smeanToZero.o smeanByRow.o svariExp.o ssvd_lancz.o dineof.o  -llapack -lblas -larpack -L/usr/lib -lnetcdff -Wl,-Bsymbolic-functions -Wl,-z,relro -lnetcdf -lnetcdf
"

I am not sure if it is showing normal output or some error is their.

Then I run "dineof.init" (Note, i am in DINEOF directory)

Outputs of running "dineof.init":
-> I have attached the modified dineof.init file. (Uploaded a .txt file, since .init is not supported here)
"
./dineof.init: line 2: INPUT: command not found
./dineof.init: line 4: Lines: command not found
./dineof.init: line 8: gappy: command not found
./dineof.init: line 9: Examples:: command not found
./dineof.init: line 10: data: command not found
./dineof.init: line 11: data: command not found
./dineof.init: line 13: data: command not found
./dineof.init: line 17: !--------------MASK: command not found
./dineof.init: line 18: Land-sea: command not found
./dineof.init: line 19: Several: command not found
./dineof.init: line 20: Example: command not found
./dineof.init: line 21: mask: command not found
./dineof.init: line 23: When: command not found
./dineof.init: line 25: mask: command not found
./dineof.init: line 27: !---------------------------------------------------------------------: command not found
./dineof.init: line 30: syntax error near unexpected token `necessary'
./dineof.init: line 30: `! time vector (necessary if B_DIFF option is activated in ppdef.h'
"

What is the issue? Please help.
[dineof.txt](https://github.com/aida-alvera/DINEOF/files/15290593/dineof.txt)

**Comment by Mr-Nobody-dey** [comment]
I am running this code for the data provided in the repository. The .dat files are produced using "gwrite.m" file.

**Comment by ctroupin** [comment]
You should run
```bash
dineof dineof.init
``

**Comment by Mr-Nobody-dey** [comment]
Thank You, it works like a charm. For others who are noob like me, run "./dineof dineof.init".

**Comment by ctroupin** [comment]
Thanks for reporting back!
Maybe we can add a line to the README in order to be more explicit.

**Comment by Mr-Nobody-dey** [comment]
That would be great, it will reduce similar questions, also reduce your job :).
